
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: subscribe to events
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.1
        inlineScript: |
            az deployment group create --resource-group newR --template-file .cloud/.azure/eventsubscribe.json
