
on: [push]

name: AzureCLISample

jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: deploy ML workspace
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.1
        inlineScript: |
          az deployment group create --resource-group vivishnoaml --template-file .cloud/.azure/deploy.json \
          --parameters .cloud/.azure/deploy.params.json patToken="533ef65eaac75541bbbe43a4dcd17df284f01a32" repo_name="mlopstemplates/CLI_Deploy"

  
